// src/data/examData.js

const examData = {
    ExamTitle: "Mathematics Final Exam",
    Description: "This is the final exam for the Mathematics course. It covers all topics.",
    ExamDate: "2025-01-20",
    Duration: "2 hours",
    Questions: [
      { id: 1, question: "What is 2 + 2?", options: ["2", "3", "4", "5"] },
      { id: 2, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 3, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 4, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 5, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 6, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 7, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 8, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 9, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 10, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 11, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 12, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 13, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 14, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 15, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 16, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 17, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 18, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 19, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 20, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 21, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 22, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 23, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 24, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 25, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 26, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 27, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 28, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 29, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 30, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 31, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 32, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 33, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 34, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 35, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 36, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 37, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 38, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 39, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 40, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 41, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 42, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 43, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 44, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 45, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 46, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 47, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 48, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 49, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
      { id: 50, question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"] },
    ],
  };
  
  export default examData;
  