export const GallaryData = [
    {
        id: 1,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"AKOLA COLLAGE",
       description: "Description for image 1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/20-B363yK_f.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/21-lj-6bVXW.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/22-pGAZNX3M.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/23-Bq576fd_.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/23-Bq576fd_.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 2,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage2",
       description: "Description for image 2",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },

    {
        id: 3,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 4,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 5,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },

    {
        id: 6,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 7,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 8,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    {
        id: 9,
        gallaryimage: 'https://www.nexusctc.com/assets/1-CFakKbv5.jpeg',
       collageName:"Collage1",
       gallaryimg1:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg2:"https://www.nexusctc.com/assets/8-80OUYS9V.jpeg",
       gallaryimg3:"https://www.nexusctc.com/assets/17-C3RtoJXi.jpeg",
       gallaryimg4:"https://www.nexusctc.com/assets/18-Bz0m7baJ.jpeg",
       gallaryimg5:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg6:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg7:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg8:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg9:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg10:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg11:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg12:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
       gallaryimg13:"https://www.nexusctc.com/assets/13-DrO_j7S7.jpeg",
    },
    
  ];
  