export const NotLoggedInData = {
    course:
        [
            {
                id: "1",
                LoggedImg: "https://techvify-software.com/wp-content/uploads/2023/09/artificial-intelligence-in-software-testing-e1695786456860.webp",
                LoggedHead: "About Software Testing",
                LogDescription: "Looking to enhance your skills with the best software training institute in Pune? Our institute offers comprehensive software testing courses designed to meet industry standards and equip you with hands-on experience. With expert trainers, real-world projects, and a proven track record of student success, we ensure you gain the knowledge and confidence needed to excel in the competitive tech landscape. Whether you're a fresher or an experienced professional, our software testing courses cater to all levels. Join the best software training institute in Pune today and take the first step toward a rewarding career in software testing.",
                LoggedDuration: " Duration: 3 Months",
                LoggedInstructor: "Saurabh Sir",
                Syllabus: "Introduction to Software Testing,Testing Fundamentals,Manual Testing Basics,Advanced Manual Testing,Automation Testing – Fundamentals,Advanced Automation Testing,Performance Testing,API Testing,Test Management Tools,Security Testing,Mobile Testing,Advanced Testing Concepts,Software Testing Certifications(Optional),Download PDF",
                pdfButton: "Download",
                Learn: "Key concepts and types of software testing (manual and automated)",
                KeyFeatures: "Key Features of the Best Software Testing Course Online: Comprehensive Curriculum: Covers manual testing, automation testing, and advanced testing methodologies. Live Interactive Classes: Real-time classes with industry experts to ensure interactive learning. Hands-on Training: Work on live projects to gain practical experience. Certification: Earn a recognized certification upon course completion. Job Placement Assistance: Support for resume building, interview preparation, and job placements. Industry-Relevant Tools: Training with tools like Selenium, JIRA, TestNG, and more. Flexible Learning Options: Choose between weekday or weekend batches as per your schedule. Doubt Resolution: Regular doubt-clearing sessions and 1-on-1 mentorship. Experienced Faculty: Learn from certified professionals with extensive industry experience. Career Guidance: Personalized career counseling to help you plan your career path in software testing.",
                TermsAndCondition: "The fees will be non-refundable and non-transferable in any circumstances,Batch or course change is not allowed.,Nexus provides corporate-level training,Training will be provided according to the specified syllabus.,Candidates will receive interview calls from different job portals,Course materials are proprietary and should not be distributed without permission.,Certification will be provided only after meeting attendance and assessment requirements.,All personal information collected will be kept confidential and used for official purposes only.,All candidates are expected to maintain professional behavior during training.,Candidates must ensure they have access to necessary hardware and software for online sessions.,Nexus is not liable for any damages arising from the use of its training services.",
            },

            {
                id: "2",
                LoggedImg: "https://techvify-software.com/wp-content/uploads/2023/09/artificial-intelligence-in-software-testing-e1695786456860.webp",
                LoggedHead: "About Software Testing",
                LogDescription: "Looking to enhance your skills with the best software training institute in Pune? Our institute offers comprehensive software testing courses designed to meet industry standards and equip you with hands-on experience. With expert trainers, real-world projects, and a proven track record of student success, we ensure you gain the knowledge and confidence needed to excel in the competitive tech landscape. Whether you're a fresher or an experienced professional, our software testing courses cater to all levels. Join the best software training institute in Pune today and take the first step toward a rewarding career in software testing.",
                LoggedDuration: " Duration: 3 Months",
                LoggedInstructor: "Abhijeet Kumar",
                Syllabus: "Introduction to Software Testing,Testing Fundamentals,Manual Testing Basics,Advanced Manual Testing,Automation Testing – Fundamentals,Advanced Automation Testing,Performance Testing,API Testing,Test Management Tools,Security Testing,Mobile Testing,Advanced Testing Concepts,Software Testing Certifications(Optional),Download PDF",
                pdfButton: "Download",
                Learn: "Key concepts and types of software testing (manual and automated)",
                KeyFeatures: "Key Features of the Best Software Testing Course Online: Comprehensive Curriculum: Covers manual testing, automation testing, and advanced testing methodologies. Live Interactive Classes: Real-time classes with industry experts to ensure interactive learning. Hands-on Training: Work on live projects to gain practical experience. Certification: Earn a recognized certification upon course completion. Job Placement Assistance: Support for resume building, interview preparation, and job placements. Industry-Relevant Tools: Training with tools like Selenium, JIRA, TestNG, and more. Flexible Learning Options: Choose between weekday or weekend batches as per your schedule. Doubt Resolution: Regular doubt-clearing sessions and 1-on-1 mentorship. Experienced Faculty: Learn from certified professionals with extensive industry experience. Career Guidance: Personalized career counseling to help you plan your career path in software testing.",
                TermsAndCondition: "The fees will be non-refundable and non-transferable in any circumstances,Batch or course change is not allowed.,Nexus provides corporate-level training,Training will be provided according to the specified syllabus.,Candidates will receive interview calls from different job portals,Course materials are proprietary and should not be distributed without permission.,Certification will be provided only after meeting attendance and assessment requirements.,All personal information collected will be kept confidential and used for official purposes only.,All candidates are expected to maintain professional behavior during training.,Candidates must ensure they have access to necessary hardware and software for online sessions.,Nexus is not liable for any damages arising from the use of its training services.",
            },
        ],
};